// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "telemetry.proto" (package "telemetry", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TelemetryActivity } from "./telemetry";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { TelemetryResponse } from "./telemetry";
import type { GameEventRequest } from "./telemetry";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service telemetry.TelemetryActivity
 */
export interface ITelemetryActivityClient {
    /**
     * @generated from protobuf rpc: ReportEvent
     */
    reportEvent(input: GameEventRequest, options?: RpcOptions): UnaryCall<GameEventRequest, TelemetryResponse>;
}
/**
 * @generated from protobuf service telemetry.TelemetryActivity
 */
export class TelemetryActivityClient implements ITelemetryActivityClient, ServiceInfo {
    typeName = TelemetryActivity.typeName;
    methods = TelemetryActivity.methods;
    options = TelemetryActivity.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ReportEvent
     */
    reportEvent(input: GameEventRequest, options?: RpcOptions): UnaryCall<GameEventRequest, TelemetryResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GameEventRequest, TelemetryResponse>("unary", this._transport, method, opt, input);
    }
}
