// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "telemetry.proto" (package "telemetry", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message telemetry.GameEventRequest
 */
export interface GameEventRequest {
    /**
     * @generated from protobuf field: string UserId = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string EventType = 2
     */
    eventType: string; // e.g., "ENEMY_FROZEN", "ICEBALL_PUSHED", "LEVEL_CLEARED"
    /**
     * @generated from protobuf field: int64 Timestamp = 3
     */
    timestamp: bigint;
    /**
     * @generated from protobuf field: int32 EntityId = 4
     */
    entityId: number;
}
/**
 * @generated from protobuf message telemetry.TelemetryResponse
 */
export interface TelemetryResponse {
    /**
     * @generated from protobuf field: bool Success = 1
     */
    success: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class GameEventRequest$Type extends MessageType<GameEventRequest> {
    constructor() {
        super("telemetry.GameEventRequest", [
            { no: 1, name: "UserId", kind: "scalar", jsonName: "UserId", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "EventType", kind: "scalar", jsonName: "EventType", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "Timestamp", kind: "scalar", jsonName: "Timestamp", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "EntityId", kind: "scalar", jsonName: "EntityId", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GameEventRequest>): GameEventRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.eventType = "";
        message.timestamp = 0n;
        message.entityId = 0;
        if (value !== undefined)
            reflectionMergePartial<GameEventRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GameEventRequest): GameEventRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string UserId */ 1:
                    message.userId = reader.string();
                    break;
                case /* string EventType */ 2:
                    message.eventType = reader.string();
                    break;
                case /* int64 Timestamp */ 3:
                    message.timestamp = reader.int64().toBigInt();
                    break;
                case /* int32 EntityId */ 4:
                    message.entityId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GameEventRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string UserId = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string EventType = 2; */
        if (message.eventType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventType);
        /* int64 Timestamp = 3; */
        if (message.timestamp !== 0n)
            writer.tag(3, WireType.Varint).int64(message.timestamp);
        /* int32 EntityId = 4; */
        if (message.entityId !== 0)
            writer.tag(4, WireType.Varint).int32(message.entityId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message telemetry.GameEventRequest
 */
export const GameEventRequest = new GameEventRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TelemetryResponse$Type extends MessageType<TelemetryResponse> {
    constructor() {
        super("telemetry.TelemetryResponse", [
            { no: 1, name: "Success", kind: "scalar", jsonName: "Success", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<TelemetryResponse>): TelemetryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<TelemetryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TelemetryResponse): TelemetryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool Success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TelemetryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool Success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message telemetry.TelemetryResponse
 */
export const TelemetryResponse = new TelemetryResponse$Type();
/**
 * @generated ServiceType for protobuf service telemetry.TelemetryActivity
 */
export const TelemetryActivity = new ServiceType("telemetry.TelemetryActivity", [
    { name: "ReportEvent", options: {}, I: GameEventRequest, O: TelemetryResponse }
]);
